'use client';

import Link from 'next/link';

/**
 * Purchase order detail — Procurement.
 * Previously missing entirely — the "new order" flow redirected here and
 * the list page linked here, both 404ing. This is also where "place order"
 * (send to supplier by email) happens.
 */

import React, { useState } from 'react';
import { useParams } from 'next/navigation';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@stayos/api-client';
import type { ApiError } from '@stayos/api-client';
import { SkeletonLoader, StatusBadge, useToast, ConfirmDialog, Icons, ReadOnlyField } from '@stayos/ui';
import { procurementKeys } from '@/lib/query-keys';

function fmtCurrency(n: number): string {
  return new Intl.NumberFormat('en-ZA', { style: 'currency', currency: 'ZAR' }).format(n || 0);
}
function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-ZA', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
}

export default function PurchaseOrderDetailPage(): React.ReactElement {
  const params = useParams<{ id: string }>();
  const poId = params.id;
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [confirmSend, setConfirmSend] = useState(false);
  const [confirmReceive, setConfirmReceive] = useState(false);

  const { data: po, isLoading } = useQuery({
    queryKey: procurementKeys.purchaseOrder(poId),
    queryFn: () => api.procurement.getPurchaseOrder(poId),
    enabled: !!poId,
  });

  const sendMutation = useMutation({
    mutationFn: () => api.procurement.sendPurchaseOrder(poId),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: procurementKeys.purchaseOrder(poId) });
      void queryClient.invalidateQueries({ queryKey: procurementKeys.purchaseOrders() });
      setConfirmSend(false);
      toast('Order placed — the supplier has been emailed.', 'success');
    },
    onError: (err: ApiError) => { setConfirmSend(false); toast(err.message ?? 'Failed to send order.', 'error'); },
  });

  const receiveMutation = useMutation({
    mutationFn: () => api.procurement.receivePurchaseOrder(poId),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: procurementKeys.purchaseOrder(poId) });
      void queryClient.invalidateQueries({ queryKey: procurementKeys.purchaseOrders() });
      void queryClient.invalidateQueries({ queryKey: procurementKeys.stockItems() });
      setConfirmReceive(false);
      toast('Order marked received — stock levels updated.', 'success');
    },
    onError: (err: ApiError) => { setConfirmReceive(false); toast(err.message ?? 'Failed.', 'error'); },
  });

  if (isLoading || !po) {
    return (
      <div data-page="purchase-order-detail">
        <div data-page-header>
          <div>
            <Link href="/procurement/purchase-orders" data-breadcrumb><Icons.ChevronLeft data-breadcrumb-icon aria-hidden="true" /> Purchase orders</Link>
            <h1>Purchase order</h1>
          </div>
        </div>
        <SkeletonLoader rows={6} />
      </div>
    );
  }

  const o = po as unknown as Record<string, unknown>;
  const status = String(o['status'] ?? 'draft');
  const supplierField = o['supplierId'];
  const supplier = (supplierField && typeof supplierField === 'object' ? supplierField : {}) as Record<string, unknown>;
  const items = Array.isArray(o['items']) ? (o['items'] as Record<string, unknown>[]) : [];

  return (
    <div data-page="purchase-order-detail">
      <div data-page-header>
        <div>
          <Link href="/procurement/purchase-orders" data-breadcrumb><Icons.ChevronLeft data-breadcrumb-icon aria-hidden="true" /> Purchase orders</Link>
          <h1>{String(o['poNumber'] ?? 'Purchase order')}</h1>
        </div>
        <div data-header-actions>
          {status === 'draft' && (
            <button type="button" data-btn-primary onClick={() => setConfirmSend(true)}>
              Place order
            </button>
          )}
          {(status === 'sent' || status === 'partially_received') && (
            <button type="button" data-btn-primary onClick={() => setConfirmReceive(true)}>
              Mark received
            </button>
          )}
        </div>
      </div>

      <div data-form-container>
        <div data-stat-grid>
          <ReadOnlyField label="Status" value={
            <>
              <StatusBadge status={status} />
              {Boolean(o['autoGenerated']) && <span data-auto-badge> · Auto-generated</span>}
            </>
          } />
          <ReadOnlyField label="Supplier" value={String(supplier['name'] ?? '—')} />
          <ReadOnlyField label="Order total" value={fmtCurrency(Number(o['totalAmount'] ?? 0))} />
        </div>
        <div data-stat-grid>
          <ReadOnlyField label="Created" value={o['createdAt'] ? fmtDate(String(o['createdAt'])) : '—'} />
          <ReadOnlyField label="Sent" value={o['sentAt'] ? fmtDate(String(o['sentAt'])) : '—'} />
          <ReadOnlyField label="Received" value={o['receivedAt'] ? fmtDate(String(o['receivedAt'])) : '—'} />
        </div>

        {status === 'draft' && !supplier['contactEmail'] && (
          <div role="alert" data-alert data-alert-warning>
            This supplier has no contact email on file — add one on the{' '}
            <Link href={`/procurement/suppliers/${String(supplier['_id'] ?? '')}`}>supplier page</Link>{' '}
            before placing this order, or it won&apos;t be able to be emailed.
          </div>
        )}

        <section data-report-section>
          <h2>Items</h2>
          <table data-table>
            <thead>
              <tr><th>Item</th><th>Quantity</th><th>Unit cost</th><th>Line total</th></tr>
            </thead>
            <tbody>
              {items.map((item, idx) => {
                const stockField = item['stockItemId'];
                const stock = (stockField && typeof stockField === 'object' ? stockField : {}) as Record<string, unknown>;
                return (
                  <tr key={idx}>
                    <td>{String(stock['name'] ?? 'Item')}</td>
                    <td>{String(item['quantity'] ?? 0)} {String(stock['unit'] ?? '')}</td>
                    <td>{fmtCurrency(Number(item['unitCost'] ?? 0))}</td>
                    <td>{fmtCurrency(Number(item['totalCost'] ?? 0))}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </section>

        {Boolean(o['notes']) && (
          <div data-form-group>
            <label>Notes</label>
            <p>{String(o['notes'])}</p>
          </div>
        )}
      </div>

      <ConfirmDialog
        open={confirmSend}
        title="Place this order?"
        message={`This will email the itemized order to ${String(supplier['name'] ?? 'the supplier')} at ${String(supplier['contactEmail'] ?? 'their contact email')} and mark it as sent.`}
        confirmLabel="Place order"
        cancelLabel="Cancel"
        onConfirm={() => sendMutation.mutate()}
        onCancel={() => setConfirmSend(false)}
      />
      <ConfirmDialog
        open={confirmReceive}
        title="Mark as received?"
        message="This records that all items have been received. Stock levels will be updated automatically — you can also add extras via Stock items → Adjust if you received more than ordered."
        confirmLabel="Mark received"
        cancelLabel="Cancel"
        onConfirm={() => receiveMutation.mutate()}
        onCancel={() => setConfirmReceive(false)}
      />
    </div>
  );
}
