import React from 'react';
import { PublicHeader, PublicFooter } from '@/components/PublicLayout';

export const metadata = {
  title: 'Privacy Policy — StayOS',
  description: 'How StayOS collects, uses and protects your personal information in accordance with POPIA.',
};

const LAST_UPDATED = '1 August 2026';

export default function PrivacyPolicyPage(): React.ReactElement {
  return (
    <>
      <PublicHeader />

      <div data-container style={{ padding: 'var(--space-12) var(--page-padding-x)', maxWidth: 800 }}>
        <div style={{ marginBottom: 'var(--space-8)' }}>
          <h1 style={{ fontSize: 'var(--text-3xl)', fontWeight: 'var(--font-bold)', marginBottom: 'var(--space-2)' }}>
            Privacy Policy
          </h1>
          <p style={{ fontSize: 'var(--text-sm)', color: 'var(--color-text-muted)' }}>
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-8)', fontSize: 'var(--text-base)', lineHeight: 'var(--leading-relaxed)', color: 'var(--color-text-secondary)' }}>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              1. Who we are
            </h2>
            <p>
              StayOS is operated by <strong>LekkerQ (Pty) Ltd</strong>, a South African company registered under the Companies Act 71 of 2008. We are a responsible party under the Protection of Personal Information Act 4 of 2013 (POPIA).
            </p>
            <p style={{ marginTop: 'var(--space-3)' }}>
              <strong>Contact:</strong> hello@stayos.co.za · The Foundry, Level 3, 16 Ebenezer Road, Salt River, Cape Town, 7925
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              2. What personal information we collect
            </h2>
            <p>We collect information you provide directly and information generated by your use of our platform:</p>
            <ul style={{ marginTop: 'var(--space-3)', paddingLeft: 'var(--space-6)', display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              <li><strong>Identity data:</strong> First name, last name, email address, phone number, South African ID number or passport number, date of birth.</li>
              <li><strong>Account data:</strong> Username, password (stored as a cryptographic hash — never in plain text), authentication method (password or Google OAuth), MFA configuration.</li>
              <li><strong>Booking and application data:</strong> Accommodation bookings, student applications, check-in and check-out dates, room preferences, special requests.</li>
              <li><strong>Payment data:</strong> Transaction records, payment method type and last four digits. Full card numbers are never stored by StayOS — they are handled by our PCI-DSS-compliant payment processors (PayFast, Ozow, Stripe).</li>
              <li><strong>Communication data:</strong> Support ticket content, complaint submissions, review text, messages sent via our platform.</li>
              <li><strong>Technical data:</strong> IP address, device type, browser, access logs. Used for security, fraud prevention and compliance.</li>
              <li><strong>Consent records:</strong> A record of every data-sharing consent you have given, including the consent text, date, time and IP address at the time of consent.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              3. How we use your information
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              {[
                { purpose: 'Providing our services', detail: 'Processing bookings, applications, payments and communications between guests, students, property operators and agencies.' },
                { purpose: 'Account management', detail: 'Creating and maintaining your account, authenticating your identity, and securing access to your data.' },
                { purpose: 'Legal compliance', detail: 'Meeting our obligations under POPIA, the Consumer Protection Act, and applicable financial regulations.' },
                { purpose: 'Fraud prevention and security', detail: 'Detecting and preventing fraudulent transactions, unauthorised access and other malicious activity.' },
                { purpose: 'Service improvement', detail: 'Analysing aggregated, anonymised usage data to improve platform features and performance.' },
                { purpose: 'Communications', detail: 'Sending booking confirmations, payment receipts, application updates and support responses. Marketing communications are only sent with your explicit opt-in consent.' },
              ].map((row) => (
                <div key={row.purpose} style={{ padding: 'var(--space-4)', background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)' }}>
                  <div style={{ fontWeight: 'var(--font-semibold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-1)' }}>{row.purpose}</div>
                  <div style={{ fontSize: 'var(--text-sm)' }}>{row.detail}</div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              4. Sharing your information
            </h2>
            <p>We share your personal information only in the following circumstances:</p>
            <ul style={{ marginTop: 'var(--space-3)', paddingLeft: 'var(--space-6)', display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              <li><strong>Property operators and agencies:</strong> When you make a booking or submit an application, the relevant property operator receives the information required to fulfil your booking. You are shown a data-sharing consent notice and must actively accept it before your information is shared. You can see a record of every consent you have given in your account.</li>
              <li><strong>Payment processors:</strong> PayFast, Ozow and Stripe receive only the payment details required to process your transaction. They operate under their own privacy policies and PCI-DSS certification.</li>
              <li><strong>Service providers:</strong> We use trusted third-party providers for email delivery, cloud hosting and analytics. All providers are bound by data processing agreements and may not use your data for their own purposes.</li>
              <li><strong>Legal requirements:</strong> We may disclose personal information if required to do so by law, court order or to protect the rights and safety of our users or the public.</li>
              <li><strong>We do not sell personal information.</strong> We do not share your data with advertisers or data brokers.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              5. Data retention
            </h2>
            <p>We retain personal information only as long as necessary for the purposes described in this policy:</p>
            <ul style={{ marginTop: 'var(--space-3)', paddingLeft: 'var(--space-6)', display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              <li>Active account data is retained for the duration of your account.</li>
              <li>Booking and payment records are retained for 5 years as required by South African financial regulations.</li>
              <li>Support and complaint records are retained for 3 years.</li>
              <li>
                <strong>Consent records are retained permanently.</strong> A record of data-sharing consents you have given cannot be erased, even after account deletion. This is a legal requirement — the record of consent forms the basis of the lawful processing that occurred under it and must be available for compliance and dispute-resolution purposes. When you request account deletion, all other personal data is removed within 30 days; consent history is not.
              </li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              6. Your rights under POPIA
            </h2>
            <p>You have the following rights regarding your personal information:</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)', marginTop: 'var(--space-3)' }}>
              {[
                { right: 'Access', detail: 'Request a copy of the personal information we hold about you via the Data Export function in your account settings.' },
                { right: 'Correction', detail: 'Update incorrect personal information directly in your profile, or contact us if a field cannot be self-corrected.' },
                { right: 'Deletion', detail: 'Request deletion of your account and personal data. See the retention policy above for what is and is not removed.' },
                { right: 'Objection', detail: 'Object to processing of your personal information for direct marketing. You can manage marketing preferences in your account settings.' },
                { right: 'Complaint', detail: 'Lodge a complaint with the Information Regulator of South Africa if you believe your rights have been violated: inforeg.org.za' },
              ].map((row) => (
                <div key={row.right} style={{ padding: 'var(--space-4)', background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', display: 'grid', gridTemplateColumns: '120px 1fr', gap: 'var(--space-3)' }}>
                  <div style={{ fontWeight: 'var(--font-semibold)', color: 'var(--color-text-primary)' }}>{row.right}</div>
                  <div style={{ fontSize: 'var(--text-sm)' }}>{row.detail}</div>
                </div>
              ))}
            </div>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              7. Security
            </h2>
            <p>
              We use industry-standard security measures including encryption at rest and in transit (TLS 1.2+), bcrypt password hashing, rate limiting, audit logging, and regular security testing. Access to personal data is restricted to authorised personnel on a need-to-know basis. Despite these measures, no system is completely secure. If you believe your account has been compromised, contact us immediately at hello@stayos.co.za.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              8. Cookies
            </h2>
            <p>
              We use strictly necessary cookies for session management (HttpOnly, Secure, SameSite=Strict). We do not use advertising or tracking cookies. The session marker cookie we write is a non-HttpOnly cookie used only to determine whether to redirect unauthenticated users — it contains no personal information or secret values.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: 'var(--text-xl)', fontWeight: 'var(--font-bold)', color: 'var(--color-text-primary)', marginBottom: 'var(--space-4)' }}>
              9. Changes to this policy
            </h2>
            <p>
              We may update this policy from time to time. Material changes will be communicated via email or a prominent notice on the platform before the change takes effect. The date at the top of this page reflects when the policy was last updated.
            </p>
          </section>

          <section style={{ padding: 'var(--space-6)', background: 'var(--color-primary-light)', borderRadius: 'var(--radius-lg)', borderLeft: '4px solid var(--color-primary)' }}>
            <h2 style={{ fontSize: 'var(--text-base)', fontWeight: 'var(--font-bold)', color: 'var(--color-primary)', marginBottom: 'var(--space-2)' }}>
              Contact our Information Officer
            </h2>
            <p style={{ fontSize: 'var(--text-sm)' }}>
              For privacy-related queries, requests or complaints, contact our Information Officer:<br />
              <strong>Email:</strong> privacy@stayos.co.za<br />
              <strong>Postal:</strong> Information Officer, LekkerQ (Pty) Ltd, The Foundry, Level 3, 16 Ebenezer Road, Salt River, Cape Town, 7925
            </p>
          </section>
        </div>
      </div>

      <PublicFooter />
    </>
  );
}
