// Curated icon set — Agency Portal + Platform Admin Portal.
//
// SKILL ui-ux-design §2 bans emoji as interface icons in any form. This file
// is the single place both Vite apps import icons from, so the set stays
// consistent instead of each page reaching for whatever looks close.
// Re-exporting (rather than each app depending on lucide-react directly)
// also means a future icon-set swap is a one-file change.
//
// Only icons actually used by Documents 13/14's pages are re-exported —
// this is a curated allowlist, not the full lucide-react surface.

export {
  // Nav / structural
  Home,
  Briefcase,
  FileText,
  Building2,
  Users,
  Receipt,
  CreditCard,
  BarChart3,
  ClipboardList,
  LifeBuoy,
  ShieldCheck,
  LayoutDashboard,
  Building,
  TrendingUp,
  Wallet,
  UserCog,
  Tag,
  Gift,
  ScrollText,
  MessageSquare,
  Star,

  // Actions / controls
  Search,
  Bell,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Plus,
  ArrowRight,
  ArrowUpRight,
  ArrowUp,
  ArrowDown,
  Minus,
  X,
  Check,
  CheckCircle2,
  Circle,
  AlertTriangle,
  AlertCircle,
  Info,
  Clock,
  Calendar,
  CalendarClock,
  Flag,
  ExternalLink,
  Download,
  Upload,
  Filter,
  MoreHorizontal,
  MoreVertical,
  Trash2,
  Pencil,
  Eye,
  EyeOff,
  LogOut,
  Menu,
  Lock,
  Unlock,
  Mail,
  Phone,
  MapPin,
  Star as StarFilled,
  RefreshCcw,
  Send,
  Paperclip,
  FileCheck2,
  FileX2,
  ShieldAlert,
  Shield,
  BadgeCheck,
  BadgeX,
  Sparkles,
  Percent,
  Banknote,
  Landmark,
  UserPlus,
  UserMinus,
  Building2 as Agency,
  ArrowLeftRight,
  ListChecks,
  History,
  Settings,
  Copy,
  MessageCircle,
  ThumbsDown,
  ThumbsUp,
  KeyRound,
  Loader2,
  Zap,
  ArrowUpDown,
  SlidersHorizontal,

  // Customer Portal additions
  GraduationCap,
  Heart,
  User,
  Headphones,
  Wifi,
  ParkingSquare,
  Coffee,
  Dumbbell,
  PawPrint,
  LayoutGrid,
  Bed,
  Crown,
  Award,
  Share2,
  Link2,
  Globe,
  Smartphone,
  MessageSquareText,
  Gem,
  Medal,
  Map,
  Palmtree,
  Lightbulb,
  BookOpen,
  PenLine,
  CalendarCheck2,
  XCircle,
  List,
  Wrench,
  DoorClosed,
} from 'lucide-react';

export type { LucideIcon, LucideProps } from 'lucide-react';
